/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiElementsRouteImport } from './routes/ui-elements'
import { Route as MinimalistPageRouteImport } from './routes/minimalist-page'
import { Route as IndexRouteImport } from './routes/index'

const UiElementsRoute = UiElementsRouteImport.update({
  id: '/ui-elements',
  path: '/ui-elements',
  getParentRoute: () => rootRouteImport,
} as any)
const MinimalistPageRoute = MinimalistPageRouteImport.update({
  id: '/minimalist-page',
  path: '/minimalist-page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/minimalist-page': typeof MinimalistPageRoute
  '/ui-elements': typeof UiElementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/minimalist-page': typeof MinimalistPageRoute
  '/ui-elements': typeof UiElementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/minimalist-page': typeof MinimalistPageRoute
  '/ui-elements': typeof UiElementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/minimalist-page' | '/ui-elements'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/minimalist-page' | '/ui-elements'
  id: '__root__' | '/' | '/minimalist-page' | '/ui-elements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MinimalistPageRoute: typeof MinimalistPageRoute
  UiElementsRoute: typeof UiElementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-elements': {
      id: '/ui-elements'
      path: '/ui-elements'
      fullPath: '/ui-elements'
      preLoaderRoute: typeof UiElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minimalist-page': {
      id: '/minimalist-page'
      path: '/minimalist-page'
      fullPath: '/minimalist-page'
      preLoaderRoute: typeof MinimalistPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MinimalistPageRoute: MinimalistPageRoute,
  UiElementsRoute: UiElementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
